version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm/v7
    environment:
      NODE_ENV: production
      TZ: Europe/Kyiv
    working_dir: /usr/src/app
    command: ["node", "./build/index.js"]